---
npm:
  platforms:
    - name: linux
      os: ubuntu
      packages:
        - libudev-dev
      architecture: x86_64
    - name: linux
      os: ubuntu
      packages:
        - libudev-dev
      architecture: x86

