---
npm:
  platforms:
    - platform: linux
      os: ubuntu
      packages:
        - "libudev-dev"
      architecture: x86_64
      node_versions:
        - "6"
        - "8"
        - "10"
    - platform: linux
      os: ubuntu
      packages:
        - "libudev-dev"
      architecture: x86
      node_versions:
        - "6"
        - "8"
        - "10"
